### ISSUE TITLE
Deprecated function: Function libxml_disable_entity_loader()

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/feeds_xpathparser#2]
`Deprecated function: Function libxml_disable_entity_loader() is deprecated in FeedsXPathParserBase->errorStart() (line 558 of /path/modules/contrib/feeds_xpathparser/FeedsXPathParserBase.inc).`

`Deprecated function: Function libxml_disable_entity_loader() is deprecated in FeedsXPathParserBase->errorStop() (line 598 of /path/modules/contrib/feeds_xpathparser/FeedsXPathParserBase.inc).`

Relevant from Feeds Tamper: https://github.com/backdrop-contrib/feeds_tamper/commit/ab446ffb7b4aa4075873348ec2865284d261ec67

**Comment by laryn** [comment]
There's an RTBC patch in the Drupal queue that does the same: https://www.drupal.org/project/feeds_xpathparser/issues/3319597

**Comment by laryn** [comment]
@Al-Rozhkov The README isn't clear -- are you the maintainer on this module? If so, I've added a PR here for consideration. If not, please let me know and I'll figure out next steps to get this merged and released.

**Comment by Al-Rozhkov** [comment]
@laryn I won't be working on this module anymore.

**Comment by laryn** [comment]
Thanks for taking the time to respond -- greatly appreciated! And thanks for your work here over the years.
